// Template padrão do Cronograma de Contratações (coluna A da planilha).
// 46 pacotes/disciplinas. Semeado por obra no 1º acesso.
export const CONTRATACAO_TEMPLATE: string[] = [
  "Demolições e Retiradas",
  "Canteiro e Proteções",
  "Topografia e Locação",
  "Drywall",
  "Forro de Gesso",
  "Forro de Gesso - Aditivo",
  "Instalações Elétricas",
  "Cabeamento Estruturado",
  "Desmontagem mobiliarios existentes",
  "Instalações Hidráulicas",
  "Sistema de Sprinklers (SPK)",
  "Sistema SDAI",
  "Civil e Acabamentos",
  "Ar Condicionado",
  "Iluminação",
  "Pedras e Marmoraria",
  "Pintura",
  "Divisórias Industriais",
  "Assentos",
  "Mobiliário Corporativo",
  "Mobiliário Decorativo",
  "Mobiliário Decorativo",
  "Mobiliário Decorativo",
  "Marcenaria",
  "Louças e Metais",
  "Louças e Metais",
  "Carpete",
  "Comunicação Visual",
  "Paisagismo",
  "Projetos Complementares",
  "Persianas",
  "Papel de Parede e Envelopamento",
  "Apoio Civil",
  "Luminárias",
  "Luminárias",
  "Luminárias",
  "Luminárias",
  "Vidro e Espelhos",
  "Piso Elevado",
  "Piso Elevado - Aditivo",
  "Porta Automática",
  "Assentamento de Revestimento",
  "Aditivo SPK",
  "Revestimento",
  "Revestimento",
  "Limpeza Pós-Obra",
];
