#!/usr/bin/env python3
"""
Seed das 20 Instruções Técnicas BÈR.
Insere via SQL direto no banco.
"""
import subprocess, sys, json

DB  = "postgresql://ber:ber2026@localhost:5432/ber_app"
UID = "0c0698e5-bfd3-48d5-88ab-5888d383bb87"  # luis.nuin@ber-engenharia.com.br (coordenacao)

def psql(sql):
    r = subprocess.run(["psql", DB, "-c", sql], capture_output=True, text=True)
    if r.returncode != 0 and "ERROR" in r.stderr:
        print(f"SQL ERR: {r.stderr[:400]}", file=sys.stderr)
    return r.stdout

def esc(s): return s.replace("'", "''") if s else ""
def arr(lst): return "ARRAY[" + ",".join(f"'{esc(x)}'" for x in lst) + "]::text[]" if lst else "ARRAY[]::text[]"
def jstr(obj): return esc(json.dumps(obj, ensure_ascii=False))

ITS = [
    {
        "code": "IT-01",
        "title": "Mobilização de Canteiro e Proteção de Áreas Comuns",
        "discipline": "outro",
        "fvs_code": "FVS_0",
        "normas": ["NR-18", "NR-6"],
        "epis": ["Capacete de segurança", "Bota de segurança com biqueira", "Colete de identificação BÈR", "Luvas de proteção"],
        "pre_requisitos": "Aprovação do condomínio/gestora\nART/RRT assinado\nVistoria de recebimento do imóvel concluída (IT-02 prévia)",
        "criterios_qualidade": "Tapume fixo, sem folgas\nCorredor limpo ao fim de cada jornada\nRota de entulho sinalizada e sem material acumulado\nRegistro fotográfico completo no sistema",
        "erros_comuns": "❌ Não proteger o piso do corredor → risco de indenização ao condomínio\n❌ Usar elevador social para materiais → conflito com condôminos\n❌ Não registrar o estado inicial do imóvel → problemas na entrega",
        "steps": [
            {"order":1,"title":"Reunião com síndico/gestora","description":"Apresentar cronograma, equipe, horários permitidos e rota de entulho. Registrar em ata."},
            {"order":2,"title":"Instalação de tapumes internos","description":"Fixar tapume de MDF ou lona vinílica na porta de entrada. Altura mínima 2,20m. Sinalizar 'OBRA EM ANDAMENTO'."},
            {"order":3,"title":"Proteção de hall e corredores","description":"Forrar o piso do corredor com papelão ou manta de proteção fixada com fita crepe (nunca fita adesiva permanente)."},
            {"order":4,"title":"Proteção de elevadores","description":"Instalar proteção de inox ou MDF nas paredes internas e piso do elevador de serviço. Confirmar elevador autorizado com síndico."},
            {"order":5,"title":"Definição da rota de entulho","description":"Identificar e sinalizar a rota completa da unidade até a caçamba/ponto de descarte. Nunca usar elevador social para entulho."},
            {"order":6,"title":"Instalação da central de materiais","description":"Definir local de armazenamento dentro da unidade. Manter organizado e limpo diariamente."},
            {"order":7,"title":"Instalação do quadro de energia provisório","description":"Se necessário, instalar tomada provisória com disjuntor identificado. Nunca usar quadro do condomínio sem autorização."},
            {"order":8,"title":"Abastecimento de água","description":"Verificar ponto de abastecimento aprovado. Nunca usar torneiras de áreas comuns sem autorização."},
            {"order":9,"title":"Registro fotográfico inicial","description":"Fotografar todos os ambientes antes de qualquer intervenção. Registrar no módulo Fotos do app."},
        ],
    },
    {
        "code": "IT-02",
        "title": "Trabalho em Edifício Ocupado",
        "discipline": "outro",
        "fvs_code": "FVS_0",
        "normas": ["NR-18", "Lei Municipal SP 15.082/2010"],
        "epis": ["Colete de identificação BÈR (todos os colaboradores)", "EPI conforme atividade em execução"],
        "pre_requisitos": "Autorização do condomínio por escrito\nIT-01 (Mobilização) concluída",
        "criterios_qualidade": "Zero notificações do condomínio por descumprimento de horário\nCorredor limpo ao término de cada jornada\nTodos os colaboradores identificados com colete BÈR",
        "erros_comuns": "❌ Iniciar atividades ruidosas antes do horário → notificação e risco de embargo\n❌ Colaboradores sem identificação → insegurança e conflito com moradores\n❌ Não comunicar incidentes → agravamento e responsabilização",
        "steps": [
            {"order":1,"title":"Horários de trabalho","description":"Respeitar estritamente os horários aprovados. Em SP: seg–sex 8h–18h, sábados 8h–13h (confirmar com cada condomínio)."},
            {"order":2,"title":"Atividades de alto ruído","description":"Britadeira, martelete, corte de cerâmica: concentrar no período autorizado (geralmente 8h–17h). Nunca iniciar antes de 8h."},
            {"order":3,"title":"Identificação da equipe","description":"Todos os colaboradores devem usar colete BÈR com nome visível. Visitantes anunciados na portaria."},
            {"order":4,"title":"Controle de acesso","description":"Nunca liberar acesso de terceiros sem comunicar à portaria. Manter lista atualizada de colaboradores autorizados."},
            {"order":5,"title":"Limpeza diária obrigatória","description":"Ao final de cada jornada: varrer corredor, recolher entulho, limpar elevador utilizado."},
            {"order":6,"title":"Comunicação com vizinhos","description":"Para atividades de impacto, comunicar com 24h de antecedência via bilhete ou app do condomínio."},
            {"order":7,"title":"Emergências","description":"Em caso de vazamento, curto ou incidente: desligar imediatamente o ponto afetado, notificar síndico e gestor em até 30 minutos."},
            {"order":8,"title":"Registro de ocorrências","description":"Qualquer reclamação de vizinho deve ser registrada no app e reportada ao gestor no mesmo dia."},
        ],
    },
    {
        "code": "IT-03",
        "title": "Demolições e Remoções",
        "discipline": "alvenaria",
        "fvs_code": "FVS_1",
        "normas": ["NR-18", "NBR 15575"],
        "epis": ["Capacete", "Óculos de proteção", "Máscara PFF2", "Luvas de raspa", "Bota com biqueira", "Protetor auricular (martelete)"],
        "pre_requisitos": "Vistoria de recebimento concluída e registrada\nProjeto executivo aprovado indicando o que demolir\nConfirmação de que paredes a demolir NÃO são estruturais\nDesligamento de circuitos elétricos e pontos hidráulicos na área",
        "criterios_qualidade": "Nenhuma parede estrutural afetada\nInstalações hidráulicas e elétricas preservadas (exceto as indicadas para remoção)\nEntulho recolhido diariamente\nRegistro fotográfico antes/depois",
        "erros_comuns": "❌ Demolir sem desligar a elétrica → choque elétrico\n❌ Não verificar se a parede é estrutural → risco de colapso\n❌ Acumular entulho por vários dias → infração ao condomínio",
        "steps": [
            {"order":1,"title":"Marcação das áreas a demolir","description":"Demarcar com giz ou fita as paredes, revestimentos e elementos a remover. Fotografar antes."},
            {"order":2,"title":"Proteção de áreas adjacentes","description":"Cobrir pisos que serão reaproveitados com papelão e manta. Selar portas de ambientes não afetados com plástico."},
            {"order":3,"title":"Desligamento elétrico","description":"Confirmar com multímetro que os circuitos da área estão sem tensão. NUNCA demolir sem verificar."},
            {"order":4,"title":"Demolição de revestimentos","description":"Iniciar pelo revestimento (porcelanato, cerâmica, massa) antes de demolir a base. Usar ponteiro e martelete."},
            {"order":5,"title":"Demolição de paredes de alvenaria","description":"Iniciar pelo topo. Nunca demolir pela base (risco de queda). Umedecer levemente para reduzir poeira."},
            {"order":6,"title":"Demolição de drywall","description":"Remover parafusos e placas. Dobrar e cortar a estrutura metálica com alicate. Reaproveitar perfis em bom estado."},
            {"order":7,"title":"Demolição de forro","description":"Remover módulos ou placas com cuidado. Verificar se há instalações acima antes de iniciar."},
            {"order":8,"title":"Segregação de entulho","description":"Separar: cerâmica/concreto em bags para caçamba; madeira/drywall separado; metais para descarte específico."},
            {"order":9,"title":"Limpeza final","description":"Varrer e recolher todo o entulho. Nunca deixar acumulado na unidade ao final do dia."},
        ],
    },
    {
        "code": "IT-04",
        "title": "Impermeabilização",
        "discipline": "impermeabilizacao",
        "fvs_code": "FVS_4",
        "normas": ["ABNT NBR 9575", "NBR 9574"],
        "epis": ["Luvas de borracha", "Óculos de proteção", "Máscara (manuseio de produtos químicos)", "Bota de PVC"],
        "pre_requisitos": "Demolição de revestimentos concluída\nRegularização do substrato (sem buracos, fissuras >3mm seladas)\nPontos hidráulicos posicionados",
        "criterios_qualidade": "Espessura mínima: 2mm (cimentício) ou conforme especificação do produto\nTeste de estanqueidade: zero perda de nível em 72h\nTela de reforço em 100% dos cantos e ralos\nRegistro fotográfico do teste no app",
        "erros_comuns": "❌ Aplicar em substrato seco sem umedecer → produto não adere corretamente\n❌ Não usar tela de reforço nos cantos → principal ponto de falha\n❌ Fazer teste com menos de 72h → resultado falso positivo\n❌ Aplicar revestimento antes do teste → se vazar, redo completo",
        "steps": [
            {"order":1,"title":"Preparação do substrato","description":"Limpar a superfície. Remover pó, graxa e resíduos. Umedecer sem encharcar."},
            {"order":2,"title":"Selagem de fissuras","description":"Fissuras até 3mm: preencher com argamassa de regularização. Aguardar cura completa (mín. 24h)."},
            {"order":3,"title":"Reforço de cantos e ralos","description":"Aplicar tela de poliéster em todos os cantos (parede/piso) e ao redor dos ralos com a 1ª demão. Sobrepor 15cm de cada lado."},
            {"order":4,"title":"1ª demão","description":"Aplicar o impermeabilizante com trincha ou rolo em movimentos horizontais. Espessura uniforme. Aguardar cura: 4–6h."},
            {"order":5,"title":"2ª demão","description":"Aplicar perpendicular à 1ª (movimentos verticais). Espessura total mínima: 2mm para cimentício. Aguardar cura: 4–6h."},
            {"order":6,"title":"3ª demão (áreas críticas)","description":"Em box de chuveiro e ralo: aplicar 3ª camada. Total ≥ 3mm."},
            {"order":7,"title":"Proteção dos ralos","description":"Tampar os ralos durante a cura para não obstruir com material."},
            {"order":8,"title":"Cura","description":"Aguardar cura mínima conforme fabricante (geralmente 72h antes do teste)."},
            {"order":9,"title":"Teste de estanqueidade","description":"Tampar o ralo. Encher com água até 3cm acima do ponto mais alto impermeabilizado. Aguardar 72 horas corridas sem reposição."},
            {"order":10,"title":"Registro","description":"Fotografar o teste (nível d'água + hora início), o resultado e o gabarito de medição."},
        ],
    },
    {
        "code": "IT-05",
        "title": "Instalações Elétricas (Bruta + Acabamento)",
        "discipline": "eletrica",
        "fvs_code": "FVS_5",
        "normas": ["ABNT NBR 5410", "NR-10"],
        "epis": ["Luvas isolantes (classe 00 para BT)", "Óculos de proteção", "Capacete", "Bota isolante", "Ferramentas com cabo isolado"],
        "pre_requisitos": "Demolições concluídas\nProjeto elétrico aprovado pelo responsável técnico\nQuadro de distribuição identificado e disjuntores desligados\n\nFase Acabamento: Drywall/alvenaria fechados, forro instalado, pintura concluída (fase bruta)",
        "criterios_qualidade": "Seção dos condutores conforme projeto e NBR 5410\nTomadas niveladas e no padrão NBR 14136\nTerra instalado em 100% dos circuitos\nQDC identificado com diagrama unifilar\nTeste de continuidade em todos os circuitos",
        "erros_comuns": "❌ Usar condutor sub-dimensionado → superaquecimento e risco de incêndio\n❌ Inverter fase e neutro → queima de equipamentos\n❌ Não instalar terra → infração à NBR 5410 e risco ao usuário\n❌ Apertar terminal sem torquímetro → mau contato e aquecimento",
        "steps": [
            {"order":1,"title":"Leitura do projeto","description":"Identificar todos os circuitos, pontos e seções de condutor conforme NBR 5410. Nunca executar de memória."},
            {"order":2,"title":"Marcação dos trajetos","description":"Marcar com giz/traçador os trajetos dos eletrodutos em paredes e teto, conforme projeto."},
            {"order":3,"title":"Abertura de rasgos","description":"Usar roçadeira elétrica. Profundidade mínima: diâmetro do eletroduto + 10mm. Em drywall: passar entre perfis."},
            {"order":4,"title":"Instalação de eletrodutos","description":"Usar corrugados flexíveis (drywall) ou rígidos PVC (alvenaria). Diâmetro mín.: 3/4\" iluminação, 1\" tomadas."},
            {"order":5,"title":"Instalação de caixas de passagem","description":"Instalar caixas 4×2\" ou 4×4\" nos pontos indicados. Nivelar com a superfície da parede."},
            {"order":6,"title":"Passagem dos condutores","description":"Passar condutores conforme seção de projeto. Deixar sobra de 30cm em cada ponto."},
            {"order":7,"title":"Identificação de circuitos","description":"Identificar cada condutor com etiqueta ou fita colorida conforme circuito. Jamais inverter fase/neutro."},
            {"order":8,"title":"Instalação do QDC","description":"Fixar o quadro nivelado. Instalar disjuntores conforme projeto. Identificar cada disjuntor com etiqueta."},
            {"order":9,"title":"Instalação de tomadas e interruptores","description":"Conectar: fase (pino direito), neutro (pino esquerdo), terra (pino central). Padrão NBR 14136."},
            {"order":10,"title":"Teste e energização","description":"Testar cada circuito com multímetro antes de energizar. Ligar um circuito de cada vez."},
        ],
    },
    {
        "code": "IT-06",
        "title": "Ar Condicionado: Infra, Equipamentos e Comissionamento",
        "discipline": "ar_condicionado",
        "fvs_code": "FVS_6",
        "normas": ["NBR 16401", "NR-35"],
        "epis": ["Capacete", "Óculos de proteção", "Luvas de raspa", "EPI para trabalho em altura (cinto, talabarte) quando necessário"],
        "pre_requisitos": "Projeto de AC aprovado\nDemolições concluídas\nEletroduto para circuito dedicado de AC disponível",
        "criterios_qualidade": "Vácuo mantido por 10 minutos sem queda\nDelta T de 8–12°C no insuflamento\nDreno escoando livremente\nIsolamento 100% da tubulação de cobre\nNenhum ruído anormal em operação",
        "erros_comuns": "❌ Não fazer vácuo → umidade no sistema → falha precoce do compressor\n❌ Tubulação de dreno sem caimento → acúmulo de água → vazamento interno\n❌ Isolar tubulação após instalação → condensação externa → gotejamento\n❌ Ligar imediatamente após instalar → queima do compressor",
        "steps": [
            {"order":1,"title":"Marcação dos pontos","description":"Marcar na parede/teto as posições das evaporadoras, condensadoras e trajeto dos dutos, conforme projeto."},
            {"order":2,"title":"Fixação dos suportes da condensadora","description":"Instalar suportes galvanizados nivelados. Verificar normas do condomínio para fachada."},
            {"order":3,"title":"Abertura de passagem para tubulação","description":"Abrir furo de 60–80mm para passagem dos tubos de cobre e dreno. Inclinar levemente para o exterior."},
            {"order":4,"title":"Instalação da tubulação de cobre","description":"Usar cobre desidratado. Dobrar com dobrador específico. Isolar com Armaflex espessura mínima 9mm."},
            {"order":5,"title":"Tubulação de dreno","description":"Instalar em PVC 3/4\" com caimento mínimo de 1% em direção ao ponto de descarte."},
            {"order":6,"title":"Fixação da evaporadora","description":"Instalar suporte nivelado. Fixar a unidade evaporadora. Verificar nível com nível de bolha."},
            {"order":7,"title":"Conexão das tubulações","description":"Conectar tubulação de cobre às válvulas da unidade com chave de torque conforme especificação do fabricante."},
            {"order":8,"title":"Vácuo","description":"Conectar bomba de vácuo. Fazer vácuo por mínimo 30 minutos (até atingir -76cmHg). Verificar se o vácuo se mantém por 10 min."},
            {"order":9,"title":"Carga de gás","description":"Liberar o gás refrigerante. Para sistemas pré-carregados: abrir válvulas de serviço."},
            {"order":10,"title":"Energização e teste","description":"Aguardar 6h antes do primeiro acionamento. Verificar: delta T 8–12°C, dreno funcionando, sem ruídos anormais."},
        ],
    },
    {
        "code": "IT-07",
        "title": "Sprinkler e SDAI",
        "discipline": "outro",
        "fvs_code": "FVS_7",
        "normas": ["NBR 10897", "NBR 17240", "IT-16 CBPMESP"],
        "epis": ["Capacete", "Óculos de proteção", "Luvas de raspa"],
        "pre_requisitos": "Autorização escrita do condomínio/gestora para despressurização\nEmpresa especializada contratada e presente\nAVCB vigente consultado\nProjeto de adaptação com ART/RRT\n\n⚠️ NUNCA intervir na rede de sprinkler sem despressurização formal.",
        "criterios_qualidade": "Zero vazamentos após repressurização\nRósulas na temperatura correta e sem danos físicos\nDetectores no espaçamento conforme NBR 17240\nART emitida e arquivada",
        "erros_comuns": "❌ Intervir sem despressurização formal → acionamento acidental do sprinkler → dano em toda a edificação\n❌ Usar rósulas de temperatura errada → acionamento acidental em dia quente\n❌ Eletroduto PVC no SDAI → não-conformidade → reprovação na vistoria",
        "steps": [
            {"order":1,"title":"Verificação do AVCB","description":"Confirmar que o AVCB do edifício está vigente. Consultar o projeto aprovado para entender a configuração atual."},
            {"order":2,"title":"Solicitação de despressurização","description":"Encaminhar requerimento formal ao síndico/gestora com data, hora, duração e escopo. Aguardar autorização por escrito."},
            {"order":3,"title":"Despressurização","description":"Empresa especializada executa o fechamento do registro de recalque e drenagem do trecho. Confirmar pressão zero com manômetro."},
            {"order":4,"title":"Adaptação da rede","description":"Executar adaptação conforme projeto aprovado. Usar materiais certificados conforme NBR 10897."},
            {"order":5,"title":"Instalação de rósulas","description":"Instalar rósulas da temperatura correta (geralmente 68°C). Verificar afastamento mínimo de obstáculos conforme norma."},
            {"order":6,"title":"Repressurização e verificação","description":"Empresa especializada restabelece a pressão. Verificar ausência de vazamentos em todos os pontos adaptados."},
            {"order":7,"title":"Instalação de detectores SDAI","description":"Detectores de fumaça: espaçamento máximo 9m entre detectores, máximo 4,5m da parede (NBR 17240)."},
            {"order":8,"title":"Testes e ART","description":"Testar cada detector com spray de teste. Verificar acionamento na central. Emitir ART/RRT e arquivar."},
        ],
    },
    {
        "code": "IT-08",
        "title": "Cabeamento Estruturado e TI",
        "discipline": "eletrica",
        "fvs_code": "FVS_8",
        "normas": ["ABNT NBR 14565", "TIA-568"],
        "epis": ["Óculos de proteção", "Luvas (passagem de cabos)"],
        "pre_requisitos": "Projeto de TI aprovado (planta de pontos)\nEletrodutos dedicados instalados (fase bruta)\nRack ou DIO definido e posicionado",
        "criterios_qualidade": "100% dos pontos certificados conforme TIA-568/NBR 14565\nRelatório de certificação emitido\nCabos identificados em ambas as extremidades\nRack organizado com organizadores de cabo",
        "erros_comuns": "❌ Usar cabo Cat5e em vez de Cat6 → limitação de velocidade e vida útil\n❌ Não certificar os pontos → problemas futuros sem rastreabilidade\n❌ Raio de curvatura forçado → degradação do sinal\n❌ Misturar padrões T568-A e T568-B → falha na conectividade",
        "steps": [
            {"order":1,"title":"Instalação do rack","description":"Fixar o rack nivelado e aterrado. Posicionar em local ventilado."},
            {"order":2,"title":"Passagem do cabo Cat6","description":"Usar cabo UTP Cat6. Raio de curvatura mínimo: 4x o diâmetro do cabo. Nunca torcer ou dobrar abruptamente."},
            {"order":3,"title":"Identificação dos cabos","description":"Etiquetar cada cabo na origem (ponto) e no destino (patch panel) com código único. Usar etiquetas termo-retráteis."},
            {"order":4,"title":"Terminação no patch panel","description":"Terminar no patch panel seguindo o padrão T568-B. Usar ferramenta de impacto (punch-down). Verificar continuidade."},
            {"order":5,"title":"Terminação nos pontos","description":"Instalar tomadas RJ45 Cat6 nas caixas 4×2\". Seguir padrão T568-B. Certificar com testador de cabo."},
            {"order":6,"title":"Organização no rack","description":"Organizar patch cords com organizadores. Usar patch cords coloridos por função."},
            {"order":7,"title":"Certificação","description":"Testar 100% dos pontos com certificador de cabo (wiremap, comprimento, atenuação, NEXT). Emitir relatório."},
            {"order":8,"title":"Documentação","description":"Atualizar planta As Built com posição de todos os pontos. Arquivar relatório de certificação."},
        ],
    },
    {
        "code": "IT-09",
        "title": "Automação e BMS",
        "discipline": "eletrica",
        "fvs_code": "FVS_9",
        "normas": ["Conforme especificação do sistema"],
        "epis": ["Luvas isolantes", "Óculos de proteção"],
        "pre_requisitos": "Cabeamento estruturado instalado e certificado (IT-08)\nElétrica de acabamento concluída (IT-05)\nProjeto de automação aprovado\n\n⚠️ Para sistemas conectados ao BMS central do condomínio: obter autorização formal antes de qualquer integração.",
        "criterios_qualidade": "100% dos cenários funcionando conforme especificação\nBackup da programação entregue\nManual de operação entregue ao cliente",
        "erros_comuns": "❌ Integrar BMS sem autorização do condomínio → conflito e desconexão\n❌ Não fazer backup da programação → perda total em caso de falha\n❌ Sensor de presença em ângulo errado → apaga a luz com sala ocupada",
        "steps": [
            {"order":1,"title":"Instalação de controladores","description":"Fixar os controladores em local ventilado e de fácil acesso para manutenção."},
            {"order":2,"title":"Cabeamento de controle","description":"Instalar cabeamento dedicado para barramento (RS485, BACnet, KNX). Nunca misturar com cabeamento de dados."},
            {"order":3,"title":"Instalação de sensores","description":"Instalar sensores de presença, temperatura e luminosidade conforme projeto. Sensor de presença a 2,4m de altura."},
            {"order":4,"title":"Instalação de painéis de controle","description":"Instalar touchscreens e botões de cenário. Altura padrão: 1,20m do piso."},
            {"order":5,"title":"Programação","description":"Realizar programação conforme especificação: cenas de iluminação, horários, integração com HVAC. Documentar cada configuração."},
            {"order":6,"title":"Teste de todos os cenários","description":"Testar 100% dos cenários programados. Verificar resposta de cada sensor e atuador."},
            {"order":7,"title":"Treinamento e documentação","description":"Apresentar o sistema ao responsável do cliente. Entregar backup da programação, As Built e manual de operação."},
        ],
    },
    {
        "code": "IT-10",
        "title": "Contrapiso e Regularização",
        "discipline": "revestimento",
        "fvs_code": "FVS_2",
        "normas": ["NBR 13816", "NBR 7200"],
        "epis": ["Bota de borracha", "Luvas de borracha", "Óculos de proteção", "Joelheira (aplicação)"],
        "pre_requisitos": "Impermeabilização concluída e aprovada no teste de estanqueidade (áreas molhadas)\nInstalações hidráulicas embutidas no piso concluídas\nTela soldada instalada (quando especificado)",
        "criterios_qualidade": "Desnivelamento máximo 3mm em régua de 2m (NBR 7200)\nEspessura mínima: 3cm em contrapiso novo; 1cm em regularização\nAusência de fissuras após cura\nSom maciço (sem oco) ao percutir",
        "erros_comuns": "❌ Não curar adequadamente → fissuras e baixa resistência\n❌ Polir a superfície → dificuldade de aderência do revestimento\n❌ Não verificar o nível antes de assentar revestimento → desnivelamento visível",
        "steps": [
            {"order":1,"title":"Limpeza do substrato","description":"Varrer e remover todo o entulho. Molhar o substrato para reduzir absorção."},
            {"order":2,"title":"Marcação do nível","description":"Usar nível laser para marcar o nível final do piso em todas as paredes. Pregar taliscas de referência a cada 1,5m."},
            {"order":3,"title":"Preparação da argamassa","description":"Traço para contrapiso: 1:4 (cimento:areia). Consistência seca para execução manual."},
            {"order":4,"title":"Aplicação e sarrafeamento","description":"Lançar a argamassa sobre o substrato. Usar régua de alumínio sobre as taliscas. Movimento de vai-e-vem horizontal."},
            {"order":5,"title":"Acabamento","description":"Desempenar com desempenadeira de madeira para textura rugosa (aderência do revestimento). Não polir."},
            {"order":6,"title":"Cura","description":"Manter úmido por 72h (cobrir com plástico ou molhar 2x ao dia). Não trafegar nas primeiras 24h."},
            {"order":7,"title":"Verificação e proteção","description":"Após cura, verificar desnivelamento com régua de 2m: tolerância máxima 3mm. Cobrir com papelão até instalação do revestimento."},
        ],
    },
    {
        "code": "IT-11",
        "title": "Drywall e Vedações",
        "discipline": "alvenaria",
        "fvs_code": "FVS_3",
        "normas": ["ABNT NBR 15758"],
        "epis": ["Óculos de proteção", "Luvas de raspa", "Máscara (poeira de gesso)", "Protetor auricular (corte de placas)"],
        "pre_requisitos": "Instalações embutidas (elétrica, hidráulica, dados) na área concluídas\nContrapiso concluído e nivelado",
        "criterios_qualidade": "Prumo máximo: 3mm em 2m\nParafusos: 1mm abaixo da superfície em toda extensão\nJuntas invisíveis após acabamento (lixamento com lixa 150)\nPlaca correta para cada ambiente (RU em áreas molhadas, RF em shafts)",
        "erros_comuns": "❌ Usar placa ST em banheiro → umidade → bolor e descolamento\n❌ Não instalar reforço para fixações pesadas → queda de objetos\n❌ Não vedar com EPDM → transmissão de ruído entre ambientes\n❌ Parafuso rasgando o papel → perda de resistência do ponto de fixação",
        "steps": [
            {"order":1,"title":"Marcação no piso e teto","description":"Marcar o eixo da parede com linha de nylon. Verificar prumo e esquadro."},
            {"order":2,"title":"Fixação das guias","description":"Fixar com parafusos/pinos a cada 60cm. Usar vedação acústica (fita de EPDM) entre guia e laje."},
            {"order":3,"title":"Montagem dos montantes","description":"Instalar montantes a cada 60cm (1 placa/face) ou 40cm (alta resistência/acústica). Verificar prumo."},
            {"order":4,"title":"Travamento e reforços","description":"Instalar travessas a cada 1,20m. Instalar reforço em OSB para fixação de objetos pesados."},
            {"order":5,"title":"Passagem das instalações","description":"Passar eletrodutos e tubulações pelos furos dos montantes. Furos máx.: 1/3 da largura do montante."},
            {"order":6,"title":"Fixação das placas — 1ª face","description":"Parafusar com parafuso phosphatizado a cada 25cm nas bordas e 30cm no campo. Cabeça: 1mm abaixo da superfície."},
            {"order":7,"title":"2ª face","description":"Fechar o outro lado com juntas das placas desencontradas (mín. 40cm) em relação à 1ª face."},
            {"order":8,"title":"Tratamento de juntas","description":"Aplicar fita de papel e massa nas juntas. 3 demãos com lixamento entre cada uma."},
            {"order":9,"title":"Arremates","description":"Instalar cantoneiras metálicas em quinas expostas. Arrematar com selante acrílico."},
        ],
    },
    {
        "code": "IT-12",
        "title": "Forro — Gesso, Drywall e Modular",
        "discipline": "acabamento",
        "fvs_code": "FVS_3A",
        "normas": ["NBR 15217"],
        "epis": ["Capacete", "Óculos de proteção", "Luvas", "Escada ou andaime adequado à altura"],
        "pre_requisitos": "Instalações de teto concluídas (elétrica, AC, sprinkler, dados)\nNível do forro marcado em todas as paredes",
        "criterios_qualidade": "Desnivelamento máximo: 3mm em régua de 2m\nPendurais a 60cm de paredes e a 1,20m entre si\nCapacidade de carga verificada para luminárias e dutos\nMódulos de borda simétricos (>30cm)",
        "erros_comuns": "❌ Pendurais mal fixados → abaulamento ou queda do forro\n❌ Não abrir furo de difusor antes de fechar o forro → retrabalho\n❌ Módulo de borda menor que 20cm → visual irregular",
        "steps": [
            {"order":1,"title":"Marcação do nível","description":"Marcar o nível do forro em todas as paredes com nível laser."},
            {"order":2,"title":"Fixação da guia perimetral","description":"Fixar guia de aço na parede no nível marcado, a cada 60cm."},
            {"order":3,"title":"Instalação dos pendurais","description":"Fixar pendurais na laje a cada 1,20m × 1,20m. Para cargas extras: pendurais a 60cm."},
            {"order":4,"title":"Instalação dos perfis de sustentação","description":"Encaixar perfis nos pendurais. Nivelar com nível laser."},
            {"order":5,"title":"Instalação dos perfis secundários","description":"Encaixar perfis perpendiculares a cada 60cm."},
            {"order":6,"title":"Abertura de furos","description":"Marcar e abrir furos para luminárias, difusores e grelhas com serra-copo antes de fechar as placas."},
            {"order":7,"title":"Fixação das placas","description":"Parafusar placa a cada 30cm nos perfis. Placas RU em copas e banheiros."},
            {"order":8,"title":"Tratamento de juntas","description":"Aplicar fita e massa nas juntas. 3 demãos com lixamento."},
        ],
    },
    {
        "code": "IT-13",
        "title": "Revestimentos Cerâmicos e Porcelanato",
        "discipline": "revestimento",
        "fvs_code": "FVS_10",
        "normas": ["NBR 13818", "NBR 14081"],
        "epis": ["Joelheira", "Óculos de proteção (corte)", "Luvas de raspa", "Protetor auricular (corte)"],
        "pre_requisitos": "Impermeabilização aprovada no teste de estanqueidade (áreas molhadas)\nContrapiso nivelado e curado\nPontos hidráulicos e elétricos posicionados",
        "criterios_qualidade": "Aderência: 100% das peças com som maciço\nPlaneza: desnivelamento máximo 3mm em 2m\nJuntas uniformes e completas com rejunte\nRejunte epóxi nas áreas molhadas",
        "erros_comuns": "❌ Usar AC-I em porcelanato → descolamento garantido\n❌ Não fazer dupla colagem → bolsos de ar → peça solta\n❌ Não usar niveladores → lipagem (desnível entre peças)\n❌ Rejuntar sem remover argamassa das juntas → rejunte superficial cai",
        "steps": [
            {"order":1,"title":"Planejamento da paginação","description":"Definir a paginação no papel. Centralizar o ambiente para que as peças de borda sejam iguais. Nunca começar sem paginação."},
            {"order":2,"title":"Escolha da argamassa","description":"AC-II para porcelanatos até 60×60cm. AC-III para porcelanatos maiores e assentamento em paredes."},
            {"order":3,"title":"Aplicação da argamassa","description":"Desempenadeira dentada: 6mm para peças até 30×30; 8mm para até 60×60; 10mm para maiores. Dupla colagem obrigatória para porcelanato."},
            {"order":4,"title":"Assentamento","description":"Posicionar a peça sobre a argamassa. Bater com martelo de borracha. Usar niveladores de placa para peças ≥30×30."},
            {"order":5,"title":"Juntas","description":"Manter espaçamento uniforme com espaçadores. Junta mínima: 1,5mm (até 60cm); 3mm (maiores). Junta de dilatação a cada 6m."},
            {"order":6,"title":"Rejuntamento","description":"Aguardar cura mínima 24h. Rejunte epóxi para áreas molhadas. Cimentício para demais áreas."},
            {"order":7,"title":"Teste de aderência","description":"Percutir 100% das peças com haste de metal: som oco indica falta de aderência → retirar e reassentar."},
        ],
    },
    {
        "code": "IT-14",
        "title": "Piso Vinílico, Laminado e Carpete",
        "discipline": "revestimento",
        "fvs_code": "FVS_10",
        "normas": [],
        "epis": ["Joelheira", "Luvas"],
        "pre_requisitos": "Contrapiso nivelado: tolerância máxima 2mm em 2m\nPiso completamente seco (umidade máxima: 3% — verificar com medidor)\nTemperatura ambiente entre 15°C e 35°C",
        "criterios_qualidade": "Planeza do substrato: máx. 2mm em 2m\nUmidade do substrato: máx. 3%\nFolga de dilatação: 8–10mm em todas as bordas\nJuntas soldadas em áreas molhadas (vinílico colado)",
        "erros_comuns": "❌ Instalar sobre substrato com umidade alta → bolhas e descolamento\n❌ Não aclimatizar as placas → dilatação após instalação → juntas abrindo\n❌ Não deixar folga de dilatação → abaulamento em dias quentes",
        "steps": [
            {"order":1,"title":"Verificação do substrato","description":"Medir umidade com medidor de umidade. Medir planeza com régua 2m. Desníveis >2mm: lixar ou aplicar massa autonivelante."},
            {"order":2,"title":"Aclimatação","description":"Deixar as caixas no ambiente por 48h antes da instalação (temperatura e umidade de equilíbrio)."},
            {"order":3,"title":"Instalação da manta de proteção","description":"Instalar manta sobre o substrato. Emendas sobrepostas em 10cm."},
            {"order":4,"title":"Marcação e planejamento","description":"Planejar sentido das tábuas (paralelo à maior dimensão). Tábuas de borda maiores que 5cm."},
            {"order":5,"title":"Instalação (Click)","description":"Encaixar tábua por tábua com ligeiro ângulo. Bater com martelo e barra de encaixe (nunca bater direto na placa)."},
            {"order":6,"title":"Bordas, rodapés e soleiras","description":"Deixar folga de 8–10mm nas bordas (dilatação). Cobrir com rodapé. Instalar perfil de transição nas portas."},
            {"order":7,"title":"Vinílico colado — solda de juntas","description":"Após 24h, realizar solda a quente com cordão de solda na mesma cor do piso (obrigatória em áreas molhadas)."},
        ],
    },
    {
        "code": "IT-15",
        "title": "Pintura — Massa Corrida e Acabamentos",
        "discipline": "acabamento",
        "fvs_code": "FVS_11",
        "normas": ["NBR 15575"],
        "epis": ["Máscara para vapores orgânicos", "Óculos de proteção", "Luvas de borracha", "Protetor auricular (lixamento mecânico)"],
        "pre_requisitos": "Drywall/alvenaria concluídos e curados\nRevestimentos cerâmicos concluídos\nElétrica bruta embutida\nForro instalado",
        "criterios_qualidade": "Cobertura uniforme sem emendas visíveis\nMínimo 2 demãos (3 em cores escuras)\nSem respingos em rodapés e revestimentos\nCantos e arremates com pincel (não rolo)",
        "erros_comuns": "❌ Pintar sobre massa úmida → bolhas e descascamento\n❌ Usar rolo com pelo muito curto em paredes texturizadas → cobertura insuficiente\n❌ Diluir tinta excessivamente → perda de cobertura e brilho\n❌ Não lixar entre demãos → acabamento com marcas de rolo",
        "steps": [
            {"order":1,"title":"Proteção","description":"Cobrir piso com plástico e fita crepe. Proteger rodapés, tomadas, interruptores e luminárias."},
            {"order":2,"title":"Correção de imperfeições","description":"Aplicar massa corrida (PVA ou acrílica) nas irregularidades. Massa acrílica obrigatória em áreas com umidade >70%."},
            {"order":3,"title":"Lixamento (1ª vez)","description":"Lixar com lixa 80 após cura da massa (24h). Remover toda poeira."},
            {"order":4,"title":"Aplicação de selador/fundo","description":"Aplicar 1 demão de selador PVA ou acrílico. Aguardar 4h."},
            {"order":5,"title":"2ª demão de massa e lixamento","description":"Aplicar 2ª demão de massa. Aguardar 24h. Lixar com lixa 120. Superfície lisa ao toque."},
            {"order":6,"title":"1ª demão de tinta","description":"Rolo de lã 12mm para paredes. Movimento em 'W' depois horizontal. Aguardar 4h."},
            {"order":7,"title":"2ª demão de tinta","description":"Direção perpendicular à 1ª. Aguardar 4h."},
            {"order":8,"title":"Retirada das proteções e retoques","description":"Retirar plásticos e fita crepe antes da tinta secar completamente (puxar em 45°). Retocar com pincel."},
        ],
    },
    {
        "code": "IT-16",
        "title": "Marcenaria e Mobiliário Fixo",
        "discipline": "marcenaria",
        "fvs_code": "FVS_12",
        "normas": [],
        "epis": ["Óculos de proteção", "Luvas", "Protetor auricular (corte)"],
        "pre_requisitos": "Pintura concluída e curada\nRevestimentos de piso instalados (ou piso referenciado para folga)\nPontos elétricos e hidráulicos posicionados dentro de armários",
        "criterios_qualidade": "Desnivelamento máximo: 1mm entre módulos adjacentes\nPortas: folga uniforme de 2mm\nTodos os módulos fixados à parede (mín. 2 pontos)\nAmortecedores funcionando em 100% das portas",
        "erros_comuns": "❌ Não nivelar a base → portas e gavetas desalinhadas impossíveis de regular\n❌ Fixar em drywall sem atingir o montante → módulo cai com uso\n❌ Não conferir medidas antes de instalar → módulo não cabe, retrabalho com custo",
        "steps": [
            {"order":1,"title":"Conferência das medidas","description":"Antes de descarregar: conferir todas as medidas dos módulos vs. o ambiente real. Diferença >5mm: reportar ao fabricante."},
            {"order":2,"title":"Marcação e nivelamento da base","description":"Marcar o posicionamento de cada módulo. Nivelar com pés reguláveis ou calços."},
            {"order":3,"title":"Fixação dos módulos","description":"Fixar à parede com parafuso e bucha conforme substrato. Mínimo 2 pontos por módulo ≥60cm."},
            {"order":4,"title":"União dos módulos","description":"Unir com parafusos confirmat a cada 30cm. Verificar alinhamento de frentes."},
            {"order":5,"title":"Instalação de portas e gavetas","description":"Instalar dobradiças e regular abertura, altura e profundidade. Instalar corrediças de gaveta e verificar curso."},
            {"order":6,"title":"Instalação de tampos","description":"Fixar tampo com silicone estrutural neutro. Granito >5kg/m²: fixar com L de aço adicionalmente."},
            {"order":7,"title":"Regulagens finais e limpeza","description":"Ajustar todas as portas e gavetas. Remover adesivos e fitas de proteção."},
        ],
    },
    {
        "code": "IT-17",
        "title": "Vidros, Divisórias e Esquadrias",
        "discipline": "vidros",
        "fvs_code": "FVS_13",
        "normas": ["NBR 7199", "NBR 16612"],
        "epis": ["Luvas de raspa (obrigatório para manuseio de vidro)", "Óculos de proteção", "Capacete", "Bota com biqueira"],
        "pre_requisitos": "Paredes, forro e piso concluídos\nVão confirmado (cotar o vão real, nunca pelo projeto)\n\n⚠️ Sempre cotar o vão real antes de cortar ou pedir o vidro.",
        "criterios_qualidade": "Vidro temperado em 100% das divisórias (NBR 7199)\nPrumo: máx. 2mm em 2m\nFolga uniforme de 3mm entre folha e marco\nVedação completa sem falhas de silicone",
        "erros_comuns": "❌ Usar vidro comum em divisória → risco de acidente + não-conformidade\n❌ Não cotar o vão real → vidro não entra ou fica folgado\n❌ Silicone ácido → corrói perfis de alumínio",
        "steps": [
            {"order":1,"title":"Cotação do vão","description":"Medir o vão em 3 alturas e 3 larguras. Usar a menor medida. Descontar folgas para perfil."},
            {"order":2,"title":"Instalação dos perfis","description":"Fixar perfis (U ou L) no piso, teto e paredes com parafuso + bucha. Nível e prumo com nível laser. Aplicar EPDM dentro do perfil."},
            {"order":3,"title":"Instalação do vidro temperado","description":"Transportar sempre na vertical. Inserir no perfil de baixo primeiro, depois no de cima. Usar ventosas para vidros >15kg."},
            {"order":4,"title":"Calços e vedação","description":"Instalar calços plásticos no fundo dos perfis. Aplicar silicone neutro (não ácido) no encontro vidro/perfil."},
            {"order":5,"title":"Esquadrias — fixação e regulagem","description":"Verificar prumo. Fixar definitivamente. Ajustar folgas e regulagem dos fechos. Folga padrão folha/marco: 3mm."},
            {"order":6,"title":"Proteção e limpeza final","description":"Manter filme de proteção até entrega. Limpar com álcool isopropílico ou produto específico para vidro."},
        ],
    },
    {
        "code": "IT-18",
        "title": "Louças, Metais e Bancadas",
        "discipline": "hidraulica",
        "fvs_code": "FVS_14",
        "normas": ["NBR 5626"],
        "epis": ["Luvas", "Óculos de proteção"],
        "pre_requisitos": "Revestimentos cerâmicos concluídos\nPontos hidráulicos (alimentação e esgoto) na posição correta\nÁgua desligada no ramal",
        "criterios_qualidade": "Zero vazamentos em todas as conexões após 24h\nDescargas funcionando sem refluxo\nSilicone contínuo sem falhas em todos os arremates\nLouças niveladas e fixas (sem balançar)",
        "erros_comuns": "❌ Não usar teflon nas roscas → vazamento garantido\n❌ Apertar excessivamente a contra-porca da torneira → quebra a bancada\n❌ Não testar antes de fechar os armários → vazamento invisível",
        "steps": [
            {"order":1,"title":"Instalação do vaso sanitário","description":"Posicionar sobre o piso. Instalar anel de vedação (cera ou PVC) na saída do esgoto. Fixar com parafusos de latão + bucha. Não apertar excessivamente."},
            {"order":2,"title":"Caixa acoplada","description":"Fixar a caixa e conectar a alimentação com tubo flexível. Apertar mão + 1/4 de volta. Ajustar boia para 2cm abaixo do overflow."},
            {"order":3,"title":"Torneiras e metais","description":"Passar pela bancada/cuba. Fixar com contra-porca. Conectar flexíveis com teflon (3 voltas). Testar sem vazamentos."},
            {"order":4,"title":"Instalação do chuveiro","description":"Fixar ramal no ponto de parede com teflon. Instalar coluna e ducha. Verificar prumo."},
            {"order":5,"title":"Bancada de granito/quartzo","description":"Confirmar medidas. Assentar com silicone neutro. Instalar cuba com grampos por baixo."},
            {"order":6,"title":"Vedação e cura","description":"Aplicar silicone neutro branco no encontro bancada/parede e bancada/cuba. Aguardar 24h antes de usar."},
            {"order":7,"title":"Teste final","description":"Abrir todos os registros. Verificar ausência de vazamentos em todas as conexões após 24h."},
        ],
    },
    {
        "code": "IT-19",
        "title": "Limpeza Técnica",
        "discipline": "outro",
        "fvs_code": "FVS_19",
        "normas": [],
        "epis": ["Luvas de borracha", "Máscara (produtos de limpeza)", "Óculos de proteção"],
        "pre_requisitos": "Todas as instalações concluídas e testadas\nMateriais e ferramentas de obra retirados\nEntulho recolhido",
        "criterios_qualidade": "Zero respingos de tinta visíveis em revestimentos, vidros e metais\nVidros sem marcas de dedo ou pó\nPiso brilhando uniformemente\nMarcenaria sem adesivos ou marcas de fita",
        "erros_comuns": "❌ Limpar piso antes de limpar paredes e teto → retrabalho\n❌ Usar esponja de aço em porcelanato → riscos permanentes\n❌ Usar produto ácido em granito → mancha a pedra\n❌ Retirar fita crepe depois de seca → arranca a tinta junto",
        "steps": [
            {"order":1,"title":"Remoção de protetores e fitas","description":"Retirar plásticos, papelões e fitas de proteção de todos os elementos. Atenção: retirar fita crepe antes de secar completamente."},
            {"order":2,"title":"Sequência obrigatória: teto → paredes → piso","description":"Sempre limpar de cima para baixo e de dentro para fora do ambiente."},
            {"order":3,"title":"Limpeza do teto e paredes","description":"Remover poeira e respingos de tinta com pano úmido. Usar espátula plástica para respingos secos."},
            {"order":4,"title":"Limpeza de vidros e esquadrias","description":"Vidros: limpar com limpa-vidros e pano de microfibra. Nunca usar esponja de aço."},
            {"order":5,"title":"Limpeza da marcenaria","description":"Remover adesivos e fitas de proteção. Limpar com pano seco ou produto específico para a laca."},
            {"order":6,"title":"Limpeza de louças e metais","description":"Usar produto específico. Remover cimentação e rejunte com espátula plástica + água."},
            {"order":7,"title":"Limpeza do piso","description":"1ª passagem: varrer todo pó e entulho fino. 2ª passagem: produto específico para cada tipo de piso."},
            {"order":8,"title":"Revisão final e áreas comuns","description":"Percorrer todos os ambientes com checklist. Limpar corredor, elevador e hall de entrada."},
        ],
    },
    {
        "code": "IT-20",
        "title": "Entrega ao Cliente",
        "discipline": "outro",
        "fvs_code": "FVS_20",
        "normas": [],
        "epis": [],
        "pre_requisitos": "Limpeza técnica (IT-19) concluída\nPunch list (Checklist 5) zerado\nTodos os sistemas testados e funcionando\nDocumentação da obra organizada",
        "criterios_qualidade": "Termo de Entrega assinado pelo cliente\nDocumentação completa entregue\nPunch list zerado antes da vistoria\nÁreas comuns devolvidas no estado original",
        "erros_comuns": "❌ Fazer vistoria com pendências abertas → cliente insatisfeito e registro de problemas\n❌ Não entregar manuais → cliente sem orientação de uso → chamados desnecessários\n❌ Não fotografar o estado final → sem registro para portfólio e para eventuais disputas",
        "steps": [
            {"order":1,"title":"Organização da documentação","description":"Separar e entregar ao cliente: manual de garantias, ART/RRT, laudos de impermeabilização, certificados de sistemas, manuais dos equipamentos."},
            {"order":2,"title":"Vistoria conjunta","description":"Percorrer todos os ambientes com o cliente. Usar o Punch List do app como roteiro. Registrar qualquer pendência em tempo real."},
            {"order":3,"title":"Demonstração dos sistemas","description":"Demonstrar operação: QDC, AC (controle remoto e app), automação (painéis e cenas), pontos de água."},
            {"order":4,"title":"Entrega das chaves e acessórios","description":"Entregar chaves dos cadeados de obra, controles remotos dos ACs, chaves de armários e demais itens."},
            {"order":5,"title":"Assinatura do Termo de Entrega","description":"Documento assinado pelo cliente confirmando recebimento e estado da obra. Fotografar o termo assinado."},
            {"order":6,"title":"Registro fotográfico final","description":"Fotografar todos os ambientes concluídos para portfólio BÈR e arquivo do projeto."},
            {"order":7,"title":"Desmobilização e comunicação ao condomínio","description":"Retirar todos os equipamentos e ferramentas. Informar ao síndico/gestora o encerramento da obra e retirada dos tapumes."},
        ],
    },
]

print(f"=== Seed de {len(ITS)} Instruções Técnicas BÈR ===\n")

for it in ITS:
    code = it["code"]
    # upsert: delete + insert
    psql(f"DELETE FROM instrucoes_tecnicas WHERE code='{code}';")
    
    steps_json = jstr(it.get("steps", []))
    
    sql = f"""
    INSERT INTO instrucoes_tecnicas (
      id, code, title, discipline, fvs_code,
      normas, epis, pre_requisitos, criterios_qualidade, erros_comuns,
      steps, materials, tools, attention_points, approval_criteria,
      status, created_by, updated_by
    ) VALUES (
      gen_random_uuid(),
      '{esc(code)}',
      '{esc(it["title"])}',
      '{esc(it["discipline"])}',
      '{esc(it.get("fvs_code",""))}',
      {arr(it.get("normas",[]))},
      {arr(it.get("epis",[]))},
      '{esc(it.get("pre_requisitos","") or "")}',
      '{esc(it.get("criterios_qualidade","") or "")}',
      '{esc(it.get("erros_comuns","") or "")}',
      '{steps_json}'::jsonb,
      '[]'::jsonb,
      '[]'::jsonb,
      '[]'::jsonb,
      '[]'::jsonb,
      'publicada',
      '{UID}',
      '{UID}'
    );"""
    r = psql(sql)
    if "INSERT 0 1" in r or "INSERT" in r:
        print(f"  ✓ {code} — {it['title'][:55]}")
    else:
        print(f"  ✗ {code} — erro")

print("\n=== Verificação ===")
r = subprocess.run(["psql", DB, "-c",
    "SELECT code, title, discipline, status FROM instrucoes_tecnicas ORDER BY code;"],
    capture_output=True, text=True)
print(r.stdout)
